{
 "title": "Disturbances",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "selected_mountpoint",
    "label": "Mountpoint",
    "query": "SELECT mountpoint_id AS __value, sitename AS __text\nFROM mountpoints\nWHERE mountpoint_id IN (SELECT DISTINCT mountpoint_id FROM rtcm_messages)"
   },
   {
    "name": "signals_gps",
    "query": "SELECT DISTINCT o.sat_signal\nFROM observations_gps o\nJOIN\n    rtcm_messages r ON o.rtcm_id = r.rtcm_id\nJOIN\n    mountpoints m ON r.mountpoint_id = m.mountpoint_id\nWHERE m.mountpoint_id = '$selected_mountpoint' AND \n$__timeFilter(r.time_received)\n ORDER BY o.sat_signal"
   },
   {
    "name": "signals_gal",
    "query": "SELECT DISTINCT o.sat_signal\nFROM observations_galileo o\nJOIN\n    rtcm_messages r ON o.rtcm_id = r.rtcm_id\nJOIN\n    mountpoints m ON r.mountpoint_id = m.mountpoint_id\nWHERE m.mountpoint_id = '$selected_mountpoint' AND \n$__timeFilter(r.time_received)\n ORDER BY o.sat_signal"
   },
   {
    "name": "signals_glo",
    "query": "SELECT DISTINCT o.sat_signal\nFROM observations_glonass o\nJOIN\n    rtcm_messages r ON o.rtcm_id = r.rtcm_id\nJOIN\n    mountpoints m ON r.mountpoint_id = m.mountpoint_id\nWHERE m.mountpoint_id = '$selected_mountpoint' AND \n$__timeFilter(r.time_received)\n ORDER BY o.sat_signal"
   },
   {
    "name": "signals_bds",
    "query": "SELECT DISTINCT o.sat_signal\nFROM observations_beidou o\nJOIN\n    rtcm_messages r ON o.rtcm_id = r.rtcm_id\nJOIN\n    mountpoints m ON r.mountpoint_id = m.mountpoint_id\nWHERE m.mountpoint_id = '$selected_mountpoint' AND \n$__timeFilter(r.time_received)\n ORDER BY o.sat_signal"
   }
  ]
 },
 "panels": [
  { "title": "Average Carrier to Noise", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "GPS CNR [dB Hz]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroupAlias(r.time_received,$__interval),\r\nAVG(CASE WHEN sat_signal = 'L1C' then obs_snr END) AS \"L1C\",\r\nAVG(CASE WHEN sat_signal = 'L1P' then obs_snr END) AS \"L1P\",\r\nAVG(CASE WHEN sat_signal = 'L1W' then obs_snr END) AS \"L1W\",\r\nAVG(CASE WHEN sat_signal = 'L1S' then obs_snr END) AS \"L1S\",\r\nAVG(CASE WHEN sat_signal = 'L1L' then obs_snr END) AS \"L1L\",\r\nAVG(CASE WHEN sat_signal = 'L1X' then obs_snr END) AS \"L1X\"\r\n,\r\nAVG(CASE WHEN sat_signal = 'L2C' then obs_snr END) AS \"L2C\",\r\nAVG(CASE WHEN sat_signal = 'L2P' then obs_snr END) AS \"L2P\",\r\nAVG(CASE WHEN sat_signal = 'L2W' then obs_snr END) AS \"L2W\",\r\nAVG(CASE WHEN sat_signal = 'L2S' then obs_snr END) AS \"L2S\",\r\nAVG(CASE WHEN sat_signal = 'L2L' then obs_snr END) AS \"L2L\",\r\nAVG(CASE WHEN sat_signal = 'L2X' then obs_snr END) AS \"L2X\"\r\n,\r\nAVG(CASE WHEN sat_signal = 'L5I' then obs_snr END) AS \"L5I\",\r\nAVG(CASE WHEN sat_signal = 'L5Q' then obs_snr END) AS \"L5Q\",\r\nAVG(CASE WHEN sat_signal = 'L5X' then obs_snr END) AS \"L5X\"\r\nFROM observations_gps o\r\nJOIN\r\n    rtcm_messages r ON o.rtcm_id = r.rtcm_id\r\nJOIN\r\n    mountpoints m ON r.mountpoint_id = m.mountpoint_id\r\nWHERE\r\n  m.mountpoint_id = '$selected_mountpoint' AND\r\n  $__timeFilter(r.time_received)\r\nGROUP BY 1"
    }
   ]
  },
  {
   "title": "Glonass CNR [dB Hz]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroupAlias(r.time_received,$__interval),\r\nAVG(CASE WHEN sat_signal = 'G1C' then obs_snr END) AS \"G1C\",\r\nAVG(CASE WHEN sat_signal = 'G1P' then obs_snr END) AS \"G1P\",\r\nAVG(CASE WHEN sat_signal = 'G2C' then obs_snr END) AS \"G2C\",\r\nAVG(CASE WHEN sat_signal = 'G2P' then obs_snr END) AS \"G2P\"\r\nFROM observations_GLO o\r\nJOIN\r\n    rtcm_messages r ON o.rtcm_id = r.rtcm_id\r\nJOIN\r\n    mountpoints m ON r.mountpoint_id = m.mountpoint_id\r\nWHERE\r\n  m.mountpoint_id = '$selected_mountpoint' AND\r\n  $__timeFilter(r.time_received)\r\nGROUP BY 1"
    }
   ]
  },
  {
   "title": "Galileo CNR [dB Hz]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroupAlias(r.time_received,$__interval),\r\nAVG(CASE WHEN sat_signal = 'E1C' then obs_snr END) AS \"E1C\",\r\nAVG(CASE WHEN sat_signal = 'E1A' then obs_snr END) AS \"E1A\",\r\nAVG(CASE WHEN sat_signal = 'E1B' then obs_snr END) AS \"E1B\",\r\nAVG(CASE WHEN sat_signal = 'E1X' then obs_snr END) AS \"E1X\",\r\nAVG(CASE WHEN sat_signal = 'E1Z' then obs_snr END) AS \"E1Z\",\r\n\r\nAVG(CASE WHEN sat_signal = 'E6C' then obs_snr END) AS \"E6C\",\r\nAVG(CASE WHEN sat_signal = 'E6A' then obs_snr END) AS \"E6A\",\r\nAVG(CASE WHEN sat_signal = 'E6B' then obs_snr END) AS \"E6B\",\r\nAVG(CASE WHEN sat_signal = 'E6X' then obs_snr END) AS \"E6X\",\r\nAVG(CASE WHEN sat_signal = 'E6Z' then obs_snr END) AS \"E6Z\",\r\n\r\nAVG(CASE WHEN sat_signal = 'E7I' then obs_snr END) AS \"E7I\",\r\nAVG(CASE WHEN sat_signal = 'E7Q' then obs_snr END) AS \"E7Q\",\r\nAVG(CASE WHEN sat_signal = 'E7X' then obs_snr END) AS \"E7X\",\r\n\r\nAVG(CASE WHEN sat_signal = 'E8I' then obs_snr END) AS \"E8I\",\r\nAVG(CASE WHEN sat_signal = 'E8Q' then obs_snr END) AS \"E8Q\",\r\nAVG(CASE WHEN sat_signal = 'E8X' then obs_snr END) AS \"E8X\",\r\n\r\nAVG(CASE WHEN sat_signal = 'E5I' then obs_snr END) AS \"E5I\",\r\nAVG(CASE WHEN sat_signal = 'E5Q' then obs_snr END) AS \"E5Q\",\r\nAVG(CASE WHEN sat_signal = 'E5X' then obs_snr END) AS \"E5X\"\r\nFROM observations_GAL o\r\nJOIN\r\n    rtcm_messages r ON o.rtcm_id = r.rtcm_id\r\nJOIN\r\n    mountpoints m ON r.mountpoint_id = m.mountpoint_id\r\nWHERE\r\n  m.mountpoint_id = '$selected_mountpoint' AND\r\n  $__timeFilter(r.time_received)\r\nGROUP BY 1"
    }
   ]
  },
  {
   "title": "BeiDou CNR [dB Hz]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroupAlias(r.time_received,$__interval),\r\nAVG(CASE WHEN sat_signal = 'B2I' then obs_snr END) AS \"B2I\",\r\nAVG(CASE WHEN sat_signal = 'B2Q' then obs_snr END) AS \"B2Q\",\r\nAVG(CASE WHEN sat_signal = 'B2X' then obs_snr END) AS \"B2X\",\r\n\r\nAVG(CASE WHEN sat_signal = 'B6I' then obs_snr END) AS \"B6I\",\r\nAVG(CASE WHEN sat_signal = 'B6Q' then obs_snr END) AS \"B6Q\",\r\nAVG(CASE WHEN sat_signal = 'B6X' then obs_snr END) AS \"B6X\",\r\n\r\nAVG(CASE WHEN sat_signal = 'B7I' then obs_snr END) AS \"B7I\",\r\nAVG(CASE WHEN sat_signal = 'B7Q' then obs_snr END) AS \"B7Q\",\r\nAVG(CASE WHEN sat_signal = 'B7X' then obs_snr END) AS \"B7X\",\r\n\r\nAVG(CASE WHEN sat_signal = 'B5D' then obs_snr END) AS \"B5D\",\r\nAVG(CASE WHEN sat_signal = 'B5P' then obs_snr END) AS \"B5P\",\r\nAVG(CASE WHEN sat_signal = 'B5X' then obs_snr END) AS \"B5X\",\r\nAVG(CASE WHEN sat_signal = 'B7D' then obs_snr END) AS \"B7D\",\r\n\r\nAVG(CASE WHEN sat_signal = 'B1D' then obs_snr END) AS \"B1D\",\r\nAVG(CASE WHEN sat_signal = 'B1P' then obs_snr END) AS \"B1P\",\r\nAVG(CASE WHEN sat_signal = 'B1X' then obs_snr END) AS \"B1X\"\r\nFROM observations_BDS o\r\nJOIN\r\n    rtcm_messages r ON o.rtcm_id = r.rtcm_id\r\nJOIN\r\n    mountpoints m ON r.mountpoint_id = m.mountpoint_id\r\nWHERE\r\n  m.mountpoint_id = '$selected_mountpoint' AND\r\n  $__timeFilter(r.time_received)\r\nGROUP BY 1"
    }
   ]
  },
  { "title": "Rapid Change Detection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "GPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__timeGroupAlias(subquery.obs_epoch,$__interval),\r\n  SUM(POWER(subquery.derivative,2)) AS \"Rapid Change\"\r\nFROM \r\n(\r\n  SELECT\r\n    o.obs_epoch,\r\n    ( o.obs_snr - LAG(o.obs_snr, 1, NULL) OVER (PARTITION BY o.sat_id, o.sat_signal ORDER BY o.obs_epoch) ) /\r\n    EXTRACT(EPOCH FROM ((o.obs_epoch - LAG(o.obs_epoch, 1, NULL) OVER (PARTITION BY o.sat_id, o.sat_signal ORDER BY o.obs_epoch))))\r\n    as derivative\r\n  FROM\r\n    observations_gps o\r\n  JOIN\r\n      rtcm_messages r ON o.rtcm_id = r.rtcm_id\r\n  JOIN\r\n      mountpoints m ON r.mountpoint_id = m.mountpoint_id\r\n  WHERE\r\n    m.mountpoint_id = '$selected_mountpoint' AND\r\n    $__timeFilter(o.obs_epoch)\r\n) subquery\r\nGROUP BY 1"
    }
   ]
  },
  {
   "title": "Glonass",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__timeGroupAlias(subquery.obs_epoch,$__interval),\r\n  SUM(POWER(subquery.derivative,2)) AS \"Rapid Change\"\r\nFROM \r\n(\r\n  SELECT\r\n    o.obs_epoch,\r\n    ( o.obs_snr - LAG(o.obs_snr, 1, NULL) OVER (PARTITION BY o.sat_id, o.sat_signal ORDER BY o.obs_epoch) ) /\r\n    EXTRACT(EPOCH FROM ((o.obs_epoch - LAG(o.obs_epoch, 1, NULL) OVER (PARTITION BY o.sat_id, o.sat_signal ORDER BY o.obs_epoch))))\r\n    as derivative\r\n  FROM\r\n    observations_GLO o\r\n  JOIN\r\n      rtcm_messages r ON o.rtcm_id = r.rtcm_id\r\n  JOIN\r\n      mountpoints m ON r.mountpoint_id = m.mountpoint_id\r\n  WHERE\r\n    m.mountpoint_id = '$selected_mountpoint' AND\r\n    $__timeFilter(o.obs_epoch)\r\n) subquery\r\nGROUP BY 1"
    }
   ]
  },
  {
   "title": "Galileo",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__timeGroupAlias(subquery.obs_epoch,$__interval),\r\n  SUM(POWER(subquery.derivative,2)) AS \"Rapid Change\"\r\nFROM \r\n(\r\n  SELECT\r\n    o.obs_epoch,\r\n    ( o.obs_snr - LAG(o.obs_snr, 1, NULL) OVER (PARTITION BY o.sat_id, o.sat_signal ORDER BY o.obs_epoch) ) /\r\n    EXTRACT(EPOCH FROM ((o.obs_epoch - LAG(o.obs_epoch, 1, NULL) OVER (PARTITION BY o.sat_id, o.sat_signal ORDER BY o.obs_epoch))))\r\n    as derivative\r\n  FROM\r\n    observations_GAL o\r\n  JOIN\r\n      rtcm_messages r ON o.rtcm_id = r.rtcm_id\r\n  JOIN\r\n      mountpoints m ON r.mountpoint_id = m.mountpoint_id\r\n  WHERE\r\n    m.mountpoint_id = '$selected_mountpoint' AND\r\n    $__timeFilter(o.obs_epoch)\r\n) subquery\r\nGROUP BY 1"
    }
   ]
  },
  {
   "title": "BeiDou",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__timeGroupAlias(subquery.obs_epoch,$__interval),\r\n  SUM(POWER(subquery.derivative,2)) AS \"Rapid Change\"\r\nFROM \r\n(\r\n  SELECT\r\n    o.obs_epoch,\r\n    ( o.obs_snr - LAG(o.obs_snr, 1, NULL) OVER (PARTITION BY o.sat_id, o.sat_signal ORDER BY o.obs_epoch) ) /\r\n    EXTRACT(EPOCH FROM ((o.obs_epoch - LAG(o.obs_epoch, 1, NULL) OVER (PARTITION BY o.sat_id, o.sat_signal ORDER BY o.obs_epoch))))\r\n    as derivative\r\n  FROM\r\n    observations_bds o\r\n  JOIN\r\n      rtcm_messages r ON o.rtcm_id = r.rtcm_id\r\n  JOIN\r\n      mountpoints m ON r.mountpoint_id = m.mountpoint_id\r\n  WHERE\r\n    m.mountpoint_id = '$selected_mountpoint' AND\r\n    $__timeFilter(o.obs_epoch)\r\n) subquery\r\nGROUP BY 1"
    }
   ]
  }
 ]
}