{
 "title": "RTCM overview",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "GPSleapseconds", "query": "18" },
   { "name": "GALleapseconds", "query": "18" },
   { "name": "GLOleapseconds", "query": "0" },
   { "name": "BEIleapseconds", "query": "4" },
   {
    "name": "countries",
    "label": "Countries",
    "query": "SELECT DISTINCT countrycode\nFROM mountpoints\nWHERE countrycode IS NOT NULL"
   },
   {
    "name": "casters",
    "label": "Casters",
    "query": "SELECT caster_id AS __value, caster AS __text FROM casters"
   },
   {
    "name": "mountpoints",
    "label": "Mountpoints",
    "query": "SELECT mountpoint_id AS __value, sitename AS __text\nFROM mountpoints\nJOIN casters ON casters.caster_id = mountpoints.caster_id\nAND casters.caster_id in ($casters)\nAND (mountpoints.countrycode in ($countries) OR mountpoints.countrycode IS NULL)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Satellite count average",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT rtcm.mountpoint,\r\n  AVG(gps_sum) AS \"GPS\",\r\n  AVG(glo_sum) AS \"GLONASS\",\r\n  AVG(gal_sum) AS \"GALILEO\",\r\n  AVG(bds_sum) AS \"BEIDOU\"\r\nFROM (\r\n  SELECT\r\n    mountpoint,\r\n    $__timeGroup(receive_time, $__interval) as time,\r\n    SUM(CASE WHEN rtcm_msg_type BETWEEN 1071 AND 1077 THEN rtcm_sat_count END)/CAST($__interval_ms/1000 AS INT) AS gps_sum,\r\n    SUM(CASE WHEN rtcm_msg_type BETWEEN 1081 AND 1087 THEN rtcm_sat_count END)/CAST($__interval_ms/1000 AS INT) AS glo_sum,\r\n    SUM(CASE WHEN rtcm_msg_type BETWEEN 1091 AND 1097 THEN rtcm_sat_count END)/CAST($__interval_ms/1000 AS INT) AS gal_sum,\r\n    SUM(CASE WHEN rtcm_msg_type BETWEEN 1121 AND 1127 THEN rtcm_sat_count END)/CAST($__interval_ms/1000 AS INT) AS bds_sum\r\n  FROM rtcm_packages\r\n  WHERE\r\n    $__timeFilter(receive_time) AND mountpoint IN ($mountpoints)\r\n  GROUP BY mountpoint, time\r\n) rtcm\r\nINNER JOIN sourcetable_constants source ON rtcm.mountpoint = source.mountpoint\r\nGROUP BY source.casterprovider, rtcm.mountpoint\r\nORDER BY source.casterprovider, rtcm.mountpoint\r\n"
    }
   ]
  },
  {
   "title": "Satellite count $__interval-average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(receive_time,$__interval),\n  mountpoint AS metric,\n  SUM(rtcm_sat_count)/($__interval_ms/1000) AS \"rtcm_sat_count\"\nFROM rtcm_packages\nWHERE\n $__timeFilter(receive_time) AND (\n  rtcm_msg_type BETWEEN 1071 AND 1077 OR\n  rtcm_msg_type BETWEEN 1081 AND 1087 OR\n  rtcm_msg_type BETWEEN 1091 AND 1097 OR\n  rtcm_msg_type BETWEEN 1121 AND 1127)\n  AND mountpoint IN ($mountpoints)\nGROUP BY time,metric \nORDER BY time,metric "
    }
   ]
  },
  {
   "title": "Mountpoint location from source table",
   "type": "geomap",
   "gridPos": { "h": 24, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT sitename, latitude, longitude\r\nFROM mountpoints\r\nWHERE mountpoint_id IN ($mountpoints)"
    }
   ]
  },
  {
   "title": "Data flow average [kB/s]",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT subquery.sitename as metric,\r\n  AVG(count_per_interval)/8/1024 AS \"kB/s average\"\r\nFROM (\r\n  SELECT\r\n    $__timeGroupAlias(r.time_received,$__interval),\r\n    m.caster_id AS caster_id,\r\n    m.sitename AS sitename,\r\n    SUM(r.msg_size)/CAST($__interval_ms/1000 AS FLOAT) AS \"count_per_interval\"\r\n  FROM rtcm_messages r \r\n  JOIN mountpoints m ON r.mountpoint_id = m.mountpoint_id\r\n  WHERE\r\n    $__timeFilter(r.time_received) AND m.mountpoint_id IN ($mountpoints)\r\n  GROUP BY 1,2,3\r\n) subquery\r\nINNER JOIN casters c ON subquery.caster_id = c.caster_id\r\nGROUP BY c.caster, subquery.sitename\r\nORDER BY c.caster, subquery.sitename\r\n\r\n\r\n"
    }
   ]
  },
  {
   "title": "Data flow $__interval-average [kB/s]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(r.time_received,$__interval),\n  m.sitename AS metric,\n  SUM(r.msg_size)/CAST($__interval_ms/1000 AS FLOAT)/8/1024 AS \"kB/s average over $__interval\"\nFROM rtcm_messages r \nJOIN mountpoints m ON r.mountpoint_id = m.mountpoint_id\nWHERE\n  $__timeFilter(r.time_received) AND m.mountpoint_id IN ($mountpoints)\nGROUP BY 1,2 \nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Disconnected mountpoints",
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  mountpoint as \"Mountpoint\",\r\n  disconnect_time as \"Disconnected at\",\r\n  reconnect_time as \"Reconnected at\",\r\n  to_char(coalesce(reconnect_time, CURRENT_TIMESTAMP)-disconnect_time, 'HH24:MI:SS') as \"Duration\"\r\nFROM connection_logger\r\nWHERE\r\n  mountpoint IN ($mountpoints) AND (\r\n    $__timeFilter(disconnect_time) OR\r\n    $__timeFilter(reconnect_time) OR\r\n    reconnect_time IS NULL)\r\nORDER BY disconnect_time DESC"
    }
   ]
  },
  {
   "title": "Coordinates [m]",
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT m.sitename as \"Mountpoint\", c.caster as \"Caster\", coord.ecef_x as \"X\", coord.ecef_y as \"Y\", coord.ecef_z as \"Z\", coord.anthgt as \"Antenna height\"\r\nFROM coordinates coord\r\nINNER JOIN mountpoints m ON coord.mountpoint_id = m.mountpoint_id\r\nINNER JOIN casters c ON c.caster_id = m.caster_id\r\nWHERE coord.mountpoint_id IN ($mountpoints)\r\nORDER BY c.caster, m.sitename"
    }
   ]
  },
  {
   "title": "Data gaps in units of $__interval",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__timeGroupAlias(r.time_received,$__interval),\r\n  m.sitename AS metric,\r\n  COUNT(r.time_received) AS \"Time received\"\r\nFROM rtcm_messages r\r\nJOIN mountpoints m ON m.mountpoint_id = r.mountpoint_id\r\nWHERE\r\n  m.mountpoint_id IN ($mountpoints) AND\r\n  $__timeFilter(r.time_received) AND (\r\n  r.msg_type BETWEEN 1071 AND 1077 OR\r\n  r.msg_type BETWEEN 1081 AND 1087 OR\r\n  r.msg_type BETWEEN 1091 AND 1097 OR\r\n  r.msg_type BETWEEN 1121 AND 1127)\r\nGROUP BY 1,2\r\nORDER BY 1,2"
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Latency of MSM $__interval-average [s]",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__timeGroup(receive_time, $__interval) AS time,\r\n  mountpoint AS metric,\r\n  AVG(MOD((EXTRACT(epoch FROM receive_time) + \r\n    CASE \r\n      WHEN rtcm_msg_type BETWEEN 1071 AND 1077 THEN $GPSleapseconds\r\n      WHEN rtcm_msg_type BETWEEN 1081 AND 1087 THEN $GLOleapseconds\r\n      WHEN rtcm_msg_type BETWEEN 1091 AND 1097 THEN $GALleapseconds\r\n      WHEN rtcm_msg_type BETWEEN 1121 AND 1127 THEN $BEIleapseconds\r\n    END)::NUMERIC(15,3),86400) - MOD((EXTRACT(epoch FROM rtcm_obs_epoch)),86400)) as value\r\nFROM rtcm_packages\r\nWHERE\r\n  mountpoint IN ($mountpoints) AND\r\n  $__timeFilter(receive_time) AND\r\n  rtcm_obs_epoch IS NOT NULL AND\r\n  rtcm_sat_count != 0 AND (\r\n  rtcm_msg_type BETWEEN 1071 AND 1077 OR\r\n  rtcm_msg_type BETWEEN 1081 AND 1087 OR\r\n  rtcm_msg_type BETWEEN 1091 AND 1097 OR\r\n  rtcm_msg_type BETWEEN 1121 AND 1127)\r\nGROUP BY 1,2\r\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Maximum latency of MSM [s]",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  MAX(receive_time) AS time,\r\n  mountpoint AS metric,\r\n  MAX(MOD((EXTRACT(epoch FROM receive_time) + \r\n    CASE \r\n      WHEN rtcm_msg_type BETWEEN 1071 AND 1077 THEN $GPSleapseconds\r\n      WHEN rtcm_msg_type BETWEEN 1081 AND 1087 THEN $GLOleapseconds\r\n      WHEN rtcm_msg_type BETWEEN 1091 AND 1097 THEN $GALleapseconds\r\n      WHEN rtcm_msg_type BETWEEN 1121 AND 1127 THEN $BEIleapseconds\r\n    END)::NUMERIC(15,3),86400) - MOD((EXTRACT(epoch FROM rtcm_obs_epoch)),86400)) as max_latency\r\nFROM rtcm_packages\r\nWHERE\r\n  mountpoint IN ($mountpoints) AND\r\n  $__timeFilter(receive_time) AND\r\n  rtcm_obs_epoch IS NOT NULL AND\r\n  rtcm_sat_count != 0 AND (\r\n  rtcm_msg_type BETWEEN 1071 AND 1077 OR\r\n  rtcm_msg_type BETWEEN 1081 AND 1087 OR\r\n  rtcm_msg_type BETWEEN 1091 AND 1097 OR\r\n  rtcm_msg_type BETWEEN 1121 AND 1127)\r\nGROUP BY metric\r\nORDER BY time ASC"
    }
   ]
  },
  {
   "title": "Minimum latency of MSM [s]",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  MAX(receive_time) AS time,\r\n  mountpoint AS metric,\r\n  MIN(MOD((EXTRACT(epoch FROM receive_time) + \r\n    CASE \r\n      WHEN rtcm_msg_type BETWEEN 1071 AND 1077 THEN $GPSleapseconds\r\n      WHEN rtcm_msg_type BETWEEN 1081 AND 1087 THEN $GLOleapseconds\r\n      WHEN rtcm_msg_type BETWEEN 1091 AND 1097 THEN $GALleapseconds\r\n      WHEN rtcm_msg_type BETWEEN 1121 AND 1127 THEN $BEIleapseconds\r\n    END)::NUMERIC(15,3),86400) - MOD((EXTRACT(epoch FROM rtcm_obs_epoch)),86400)) as max_latency\r\nFROM rtcm_packages\r\nWHERE\r\n  mountpoint IN ($mountpoints) AND\r\n  $__timeFilter(receive_time) AND\r\n  rtcm_obs_epoch IS NOT NULL AND\r\n  rtcm_sat_count != 0 AND (\r\n  rtcm_msg_type BETWEEN 1071 AND 1077 OR\r\n  rtcm_msg_type BETWEEN 1081 AND 1087 OR\r\n  rtcm_msg_type BETWEEN 1091 AND 1097 OR\r\n  rtcm_msg_type BETWEEN 1121 AND 1127)\r\nGROUP BY metric\r\nORDER BY time ASC"
    }
   ]
  }
 ]
}