CREATE TABLE IF NOT EXISTS mountpoints (
    mountpoint_id SERIAL PRIMARY KEY,
    caster_id INT, -- REFERENCES casters(caster_id) ON DELETE CASCADE,
    mountpoint VARCHAR(100) NOT NULL,
    identifier VARCHAR(100),
    format TEXT,
    format_details TEXT,
    carrier INT,
    nav_system TEXT,
    network TEXT,
    country VARCHAR(3),
    latitude NUMERIC(5,2),
    longitude NUMERIC(5,2),
    nmea INT,
    solution INT,
    generator TEXT,
    compr_encryp TEXT,
    authentication VARCHAR(1),
    fee VARCHAR(1),
    bitrate INT,
    misc TEXT,
    UNIQUE (caster_id, mountpoint)
);
